name: Deploy to FTP

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 📂 Sync files - Production
        uses: SamKirkland/FTP-Deploy-Action@v4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "./test-wafu.ad-ong.org/"
          local-dir: "./back-end/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**