name: Deploy to FTP

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables - Production
        run: |
          echo "APP_NAME=WafuPay" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=base64:+1hgX+SrJHhhUyGgJb0h2QAJoNX6JwmoQLJX68LKuYY=" >> .env
          echo "APP_URL=https://test-wafu.ad-ong.org" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: 📂 Sync files - Production
        uses: SamKirkland/FTP-Deploy-Action@v4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "./test-wafu.ad-ong.org/"
          local-dir: "./back-end/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**